package main

const (
	registerHTMLPage = `<!DOCTYPE html>
<html><head><meta name="GCD" content="YTk3ODQ3ZWZhN2I4NzZmMzBkNTEwYjJlcec4be180d474f9b392dcc2691b60bf4"/>
  <meta charset="utf-8">
  <title>Register!</title>
  <meta name="generator" content="Google Web Designer 5.0.4.0226">
  <style type="text/css" id="gwd-text-style">p{margin:0px}h1{margin:0px}h2{margin:0px}h3{margin:0px}</style>
  <style type="text/css">html,body{width:100%;height:100%;margin:0px}body{transform:matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1);perspective:1400px;transform-style:preserve-3d;background-image:none;background-color:#494dda}[data-gwd-group="registration-group"]{width:1202.99px;height:717.986px}.gwd-div-1wbp{position:absolute;left:0px;top:0px}.gwd-form-8xac{position:absolute;background-image:none;background-color:#fff;width:51.7%;left:24.19%;top:19.64%;height:55.29%;transform-origin:310.938px 198.14px 0px;border-radius:8px}.gwd-p-107o{position:absolute;transform-style:preserve-3d;text-align:center;top:12.34%;font-family:Verdana;margin:0px;width:76.37%;left:11.815%;height:36.78%;transform-origin:237.875px 73.5531px 0px;overflow:auto;transform:translate3d(0, -23px, 0)}.gwd-input-1y1p{position:absolute;width:50.17%;height:5.04%;border-color:#4294e8;border-image-source:none;border-image-width:1;border-image-outset:0;border-image-repeat:stretch;border-style:solid;transform-style:preserve-3d;border-radius:5px;border-width:2px;padding:2px 6px;left:24.915%;top:47.48%;transform-origin:164.008px 16px 0px;transform:translate3d(-23px, 3px, 0)}.gwd-button-1tt6{position:absolute;height:6.05%;width:13.67%;border-style:solid;border-image-source:none;border-image-width:1;border-image-outset:0;border-image-repeat:stretch;border-color:#4294e8;border-radius:4px;background-image:none;background-color:#fff;margin:15px;top:77%;left:43.165%;transform-style:preserve-3d;transform:translate3d(-15px, -21px, 0);padding-bottom:2px;padding-top:2px}input[type="text"]{outline:none;margin:15px}input[type="text"]:focus{box-shadow:#4294e8 0 0 5px}</style>
  <script type="text/javascript" gwd-events="support">var gwd=gwd||{};gwd.actions=gwd.actions||{};gwd.actions.events=gwd.actions.events||{};gwd.actions.events.getElementById=function(id){var element=document.getElementById(id);if(!element){var pageDeck=document.querySelector("gwd-pagedeck")||document.querySelector("[is=gwd-pagedeck]");if(pageDeck){if(typeof pageDeck.getElementById==="function"){element=pageDeck.getElementById(id)}}}if(!element){switch(id){case"document.body":element=document.body;break;case"document":element=document;break;case"window":element=window;break;default:break}}return element};gwd.actions.events.addHandler=function(eventTarget,eventName,eventHandler,useCapture){var targetElement=gwd.actions.events.getElementById(eventTarget);if(targetElement){targetElement.addEventListener(eventName,eventHandler,useCapture)}};gwd.actions.events.removeHandler=function(eventTarget,eventName,eventHandler,useCapture){var targetElement=gwd.actions.events.getElementById(eventTarget);if(targetElement){targetElement.removeEventListener(eventName,eventHandler,useCapture)}};gwd.actions.events.setInlineStyle=function(id,styles){var element=gwd.actions.events.getElementById(id);if(!element||!styles){return}var transitionProperty=element.style.transition!==undefined?"transition":"-webkit-transition";var prevTransition=element.style[transitionProperty];var splitStyles=styles.split(/\s*;\s*/);var nameValue;splitStyles.forEach(function(splitStyle){if(splitStyle){var regex=new RegExp("[:](?![/]{2})");nameValue=splitStyle.split(regex);nameValue[1]=nameValue[1]?nameValue[1].trim():null;if(!(nameValue[0]&&nameValue[1])){return}element.style.setProperty(nameValue[0],nameValue[1])}});function restoreTransition(event){var el=event.target;el.style.transition=prevTransition;el.removeEventListener(event.type,restoreTransition,false)}element.addEventListener("transitionend",restoreTransition,false);element.addEventListener("webkitTransitionEnd",restoreTransition,false)}</script>
  <script type="text/javascript" gwd-events="handlers">gwd.auto_HotpMouseover=function(event){gwd.actions.events.setInlineStyle("submit","transition: all 0.2s ease; background-color: #4294e8;")};gwd.auto_HotpMouseleave=function(event){gwd.actions.events.setInlineStyle("submit","transition: all 0.2s ease; background-color: #ffffff;")};gwd.auto_SubmitMousedown=function(event){gwd.actions.events.setInlineStyle("submit","box-shadow: rgb(66, 148, 232) 0px 0px 5px;")}</script>
  <script type="text/javascript" gwd-events="registration">gwd.actions.events.registerEventHandlers=function(event){gwd.actions.events.addHandler("submit","mouseover",gwd.auto_HotpMouseover,false);gwd.actions.events.addHandler("submit","mouseleave",gwd.auto_HotpMouseleave,false);gwd.actions.events.addHandler("submit","mousedown",gwd.auto_SubmitMousedown,false)};gwd.actions.events.deregisterEventHandlers=function(event){gwd.actions.events.removeHandler("submit","mouseover",gwd.auto_HotpMouseover,false);gwd.actions.events.removeHandler("submit","mouseleave",gwd.auto_HotpMouseleave,false);gwd.actions.events.removeHandler("submit","mousedown",gwd.auto_SubmitMousedown,false)};document.addEventListener("DOMContentLoaded",gwd.actions.events.registerEventHandlers);document.addEventListener("unload",gwd.actions.events.deregisterEventHandlers)</script>
</head>

<body class="htmlNoPages">
  <form action="/register" method="post" class="gwd-form-8xac">
    <p class="gwd-p-107o" id="welcome-message">Welcome to Michaels HOTP and TOTP demo! This demo is set up to demonstrate HOTP and TOTP by having you register an email address (no emails will be sent to you) then redirecting you to a page where you can register both a HOTP and TOTP key with an
      app like Authy. On following pages, the application allows testing those HOTP and TOTP codes</p>
    <input type="text" name="email" id="email" class="gwd-input-1y1p" data-gwd-name="email" placeholder="Email" style="background-color: transparent;">
    <button type="submit" class="gwd-button-1tt6" id="submit" data-gwd-name="submit">Register!</button>
  </form>


</body></html>

`
)
